### PR TITLE
Scanning page filtering updates

### PR DESCRIPTION
**Pull request by dannygoldstein**
Adds a migration script and indexes newly filtered column  `passed_at`

### CODE REVIEW

**Comment by acrellin** [comment]
@dannygoldstein the diff looks way off. Need to rebase?

**Comment by dannygoldstein** [comment]
Nah I just merged master on my branch. This fixed up the merge conflicts

**Review by dmitryduev — CHANGES_REQUESTED** [review]
Hey @dannygoldstein what's up with all the followup requests stuff here, shouldn't it be removed?
Also, for the migration, since passed_at becomes non-nullable, we need to fill the nulls with the corresponding `Obj.created_at`.
Thanks!

**Comment by dannygoldstein** [comment]
@dmitryduev I merged master into this branch, so the diff against ari's
branch reflects those changes - ari do you want to merge master into your
branch to reduce the diff ?

Will update the migration.

**Comment by dmitryduev** [comment]
ah, I see, thanks @dannygoldstein

**Comment by acrellin** [comment]
@dannygoldstein please cherry-pick the relevant commits onto a branch based on this one, not on master. that's how PRs work. This diff is off

**Pull request closed without merging**
